### ISSUE TITLE
Support for Visual Studio 2017

### ISSUE THREAD

**Issue by bblaszkow06** [membraneframework/bundlex#11]
with Visual Studio 2017 Build Tools this toolchain won't work, the directory structure has been changed. I guess it won't be a priority, so the README  might mention that

**Comment by WolfDan** [comment]
Visual Studio 2017 has `vcvarsall` at the path `C:\Program Files (x86)\Microsoft Visual Studio\2017\VERSION\VC\Auxiliary\Build`, in my case I'd use Proffesional so the path is `C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\VC\Auxiliary\Build`

I've tried to use the library as ENV variable, but the library join the path like `ENV + /VC/vcvarsall.bat` which does not work in this case 

So not sure what to do in this case to solve the issue

**Comment by abhijeetbhagat** [comment]
Have the same problem. I am using VS 2019 Community and the `vcvarsall` script is inside `C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Auxiliary\Build`
I've also tried setting the `VISUAL_STUDIO_ROOT` to point to the above path but Bundlex still can't find it and says `Unable to find vcvarsall.bat script within Visual Studio root directory. Is your Visual Studio installation valid? (and file is in VC directory?)`
