### ISSUE TITLE
Paths with special characters on Windows

### ISSUE THREAD

**Issue by bblaszkow06** [membraneframework/bundlex#21]
When project using Bundlex is placed in directory with path containing Unicode characters (such as `ł`, `Ą` or `ó`), building script will fail. The workaround is to set console code page to utf-8 (with `chcp 65001` command) or change used directory

**Comment by mat-hek** [comment]
Closing as Windows compatibility is currently not maintained. However, contributions are welcome - feel free to reopen for that purpose.
