### ISSUE TITLE
Unify compilation process between macOS and Linux

### ISSUE THREAD

**Issue by bblaszkow06** [membraneframework/bundlex#32]
On macOS, the compilation is done in the single stage while Linux with GCC creates intermediate `.o` files stored right next to `.c`.
The options are:
* Use one pass on both systems
* use two passes on macOS and Linux + fix paths for `.o` files (they should probably be stored in build catalogue)
* instead of manual script creation, generate a description for an existing build system (like ninja or make)

**Comment by mat-hek** [comment]
partially fixed in #36, closing in favour of #39
