### ISSUE TITLE
Add support for custom resolution of the linker/compilation flags

### ISSUE THREAD

**Issue by mspanc** [membraneframework/bundlex#34]
There are some corner cases such as the lame element, that cannot be handled easily with current approach to determine linker/compiler flags via pkg-config.

LAME library does not ship with pkg-config file, neither on the most popular Linux distributions such as Debian/Ubuntu nor when installed via brew on Mac OS X.

Current requirement to install the .pc file manually is not nice, error-prone and it is not cross platform.

There should be an option in bundlex to define custom callbacks that will determine the proper compiler/linker flags when needed.

**Comment by mat-hek** [comment]
solved in #38

**Comment by mat-hek** [comment]
solved in #38
