### ISSUE TITLE
instead of manual script creation, generate a description for an existing build system

### ISSUE THREAD

**Issue by mat-hek** [membraneframework/bundlex#39]
... such as ninja or make

**Comment by bblaszkow06** [comment]
We can use makefile along with https://github.com/elixir-lang/elixir_make

**Comment by mkaput** [comment]
The issue with elixir_make is that it depends on `nmake` on Windows, which is super incompatible with GNU/BSD make. I think it might be better to distribute Ninja binaries along with Bundlex (these are single-file executables). Ninja is Apache-licensed so licensing should not be a problem.
