### ISSUE TITLE
Unable to compile on Windows with MSVC and Professional 2019

### ISSUE THREAD

**Issue by fire** [membraneframework/bundlex#81]
Unable to compile on Windows with MSVC and Professional 2019.

How to fix?

It's related to a few other issues because this version msvc changed.

**Comment by mat-hek** [comment]
Hi @fire,

thanks for trying Bundlex on Windows. Investigating that is in our roadmap, but since we don't use Windows, it doesn't have high priority, so we cannot provide the fix for now, unfortunately.
