### ISSUE TITLE
Enhance info about missing native libraries

### ISSUE THREAD

**Issue by mickel8** [membraneframework/bundlex#90]
At this moment, if some native library is missing user will see in most cases info about missing `.pc` file which isn't too meaningful.

The task is to enhance info about missing native libraries so that user will see info similar to:

for Ubuntu:
```
You are missing ffmpeg in your OS.
To install it run `apt install ffmpeg`.
````

for MacOS:
```
You are missing ffmpeg in your OS.
To install it run `brew install ffmpeg`.
````

**Comment by mat-hek** [comment]
done in #105
