### ISSUE TITLE
Unable to compile for MSVC 2022

### ISSUE THREAD

**Issue by fire** [membraneframework/bundlex#95]
>mix test
==> bundlex
Compiling 8 files (.ex)
warning: unused alias Output
  lib/bundlex/toolchain/llvm_mingw.ex:8

warning: unused alias PathHelper
  lib/bundlex/toolchain/llvm_mingw.ex:6

could not compile dependency :example_lib, "mix compile" failed. Errors may have been logged above. You can recompile this dependency with "mix deps.compile example_lib", update it with "mix deps.update example_lib" or clean it with "mix deps.clean example_lib"
==> example_lib
** (Mix) Bundlex: Unable to find Visual Studio root directory. Please ensure that it is either located in "c:\Program Files (x86)\Microsoft Visual Studio *" or VISUAL_STUDIO_ROOT environment variable pointing to its root is set.
==> example

**Comment by alfredbaudisch** [comment]
@fire have you ever manage to compile it for Windows?

I fixed the problem you reported by finding where `vcvarsall.bat` was installed on my system. Then I copy and pasted it into `C:\Program Files\Microsoft Visual Studio\2022\Community\VC\vcvarsall.bat`.

But then I get other errors:

```
** (FunctionClauseError) no function clause matching in Bundlex.Toolchain.VisualStudio.compiler_comm
ands/1

    The following arguments were given to Bundlex.Toolchain.VisualStudio.compiler_commands/1:

        # 1
        %Bundlex.Native{name: :lib, app: :bunch_native, type: :lib, includes: ["c:/Program Files/Erl
ang OTP/usr/include", "p:/dev/elixir/sources/rayex/deps/bunch_native/c_src/bunch/bunch/.."], libs: [
], lib_dirs: [], pkg_configs: [], sources: ["p:/dev/elixir/sources/rayex/deps/bunch_native/c_src/bun
ch/bunch/lib.c"], deps: [], compiler_flags: [], linker_flags: [], language: :c, interface: nil, prep
rocessors: []}

    Attempted function clauses (showing 1 out of 1):

        def compiler_commands(-%Bundlex.Native{interface: :nif} = native-)

    (bundlex 1.1.1) Bundlex.Toolchain.VisualStudio.compiler_commands/1
    (bundlex 1.1.1) lib/bundlex/native.ex:107: Bundlex.Native.resolve_native/4
    (bunch 1.6.0) lib/bunch/enum.ex:244: Bunch.Enum.do_try_flat_map/3
    (bundlex 1.1.1) lib/mix/tasks/compile.bundlex.ex:40: Mix.Tasks.Compile.Bundlex.run/1
    (mix 1.14.3) lib/mix/task.ex:421: anonymous fn/3 in Mix.Task.run_task/4
    (mix 1.14.3) lib/mix/tasks/compile.all.ex:92: Mix.Tasks.Compile.All.run_compiler/2
    (mix 1.14.3) lib/mix/tasks/compile.all.ex:72: Mix.Tasks.Compile.All.compile/4
    (mix 1.14.3) lib/mix/tasks/compile.all.ex:59: Mix.Tasks.Compile.All.with_logger_app/2
```

**Comment by fire** [comment]
I was never able to get this to work. Please help if you can.
